services:
  # This service MUST have the name "kdc-kadmin" otherwise every kerberos client won't be able to talk with the KDC.
  # If you would like to change the name edit the file configureKerberosClient.sh and change the configurations
  # "kdc" and "admin_server" in the /etc/krb5.conf section.
  kdc-kadmin:
    build: ./kdc-kadmin
    env_file: kerberos.env
    environment:
      HOST_HOSTNAME: ${HOST_HOSTNAME}
      HOST_USER: ${HOST_USER}
    ports:
      - 88:88
      - 88:88/udp
      - 749:749
      - 749:749/udp
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
      - ./keytabs:/keytabs
    networks:
      - ldap

  kerberos-client:
    build: ./kerberos-client
    env_file: kerberos.env
    depends_on:
      - kdc-kadmin

  nfs:
    image: erichough/nfs-server
    hostname: nfs-server
    # environment:
    #   NFS_ENABLE_KERBEROS: 0
    cap_add:
      - SYS_ADMIN
    # privileged: true
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    volumes:
      # - type: bind
      #   source: ./keytabs/nfs-server.keytab
      #   target: /etc/krb5.keytab
      #   read_only: true
      # - type: bind
      #   source: ./krb5.conf
      #   target: /etc/krb5.conf
      #   read_only: true
      - type: bind
        source: exports
        target: /etc/exports
      - ./data:/data
    depends_on:
      - kdc-kadmin
    networks:
      - ldap
    
  openldap:
    build:
      context: ./
    hostname: ${HOST_HOSTNAME}
    entrypoint: ['bash', '-c', 'usr/sbin/container ; sleep 10 && /tmp/load-config.sh']
    ports:
      - 389:3890
      - 636:6360
    environment:
      OPENLDAP_BOOTSTRAP_ORGANIZATION: "Example Inc" 
      OPENLDAP_BOOTSTRAP_SUFFIX: "dc=example,dc=local"
      OPENLDAP_BOOTSTRAP_TLS: true
      OPENLDAP_BOOTSTRAP_TLS_REQUIRED: false
      OPENLDAP_BOOTSTRAP_SCHEMAS: "core.ldif cosine.ldif inetorgperson.ldif nis.ldif"
      OPENLDAP_BOOTSTRAP_FRONTEND_PASSWORD_HASH: "{ARGON2}"
      OPENLDAP_BOOTSTRAP_CONFIG_ROOT_PASSWORD_HASHED: ${LDAP_PASSWORD_HASHED}
      OPENLDAP_BOOTSTRAP_DATA_ROOT_PASSWORD_HASHED: ${LDAP_PASSWORD_HASHED}
    volumes:
      - openldap-conf:/etc/openldap/slapd.d
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-backups:/var/lib/openldap/openldap-backups
      - type: bind
        source: ./keytabs/openldap-server.keytab
        target: /etc/krb5.keytab
        read_only: true
      - type: bind
        source: ./krb5.conf
        target: /etc/krb5.conf
        read_only: true
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -lntu | grep -qa 3890"]
      interval: 2s
      timeout: 1s
      retries: 100
      start_period: 10s
    networks:
      ldap:
        aliases:
          - openldap
    depends_on:
      - kdc-kadmin

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False}, {'port': 3890}]}, {'login': [{'bind_id': 'cn=admin,dc=example,dc=local'}, {'bind_pass': '$LDAP_PASSWORD'}]}]}]"
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: cert.crt
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: cert.key
      PHPLDAPADMIN_HTTPS_CA_FILENAME: ca.crt
    depends_on:
      - openldap
    volumes:
      - ./certs:/container/service/phpldapadmin/assets/apache2/certs
    networks:
      - ldap

  setup-ldap:
    image: alpine:latest
    build:
      context: ./custom/
    depends_on:
      openldap:
        condition: service_healthy
    environment:
      LDAP_PASSWORD: ${LDAP_PASSWORD}
    networks:
      - ldap

networks:
  ldap:

volumes:
  openldap-conf:
  openldap-data:
  openldap-backups:


# NOTE:
#  "env_file: kerberos.env" is optional.
#  In case no .env file is supplied, nor any environment variable is set, the following values will be used:
#   REALM=EXAMPLE.COM
#   SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
#   KADMIN_PRINCIPAL=kadmin/admin
#   KADMIN_PASSWORD=MITiys4K5
